force-app/main/default/objects/Language_Course__c/Language_Course__c.object-meta.xml
<CustomObject>
    <label>Language Course</label>
    <nameField>
        <label>Language Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Language_Course__c/fields/Course_Instructor__c.field-meta.xml
<CustomField>
    <fullName>Course_Instructor__c</fullName>
    <description>Teacher for the language course</description>
    <label>Course Instructor</label>
    <referenceTo>Language_Course_Instructor__c</referenceTo>
    <relationshipLabel>Language Courses</relationshipLabel>
    <relationshipName>Language_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Language_Course_Instructor__c/Language_Course_Instructor__c.object-meta.xml
<CustomObject>
    <!--<gender>Feminine</gender>-->
    <label>Language Course Instructor</label>
    <nameField>
        <label>Language Course Instructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Course Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/Classes/TestLanguageCourseTrigger.cls
@isTest
private class TestLanguageCourseTrigger { 
    @isTest static void TestLanguageCourseTrigger() {
        // Test data setup
        //Creamos un instructor para el
        Language_Course_Instructor__c instructor = new Language_Course_Instructor__c(Name='Test Language Course Instructor');
        insert instructor;
        // Create an curso
        Language_Course__c curso = new Language_Course__c(Name='Test Language Course', Course_Instructor__c=instructor.Id);
        insert curso;
                
        // Perform test
        Test.startTest();
        Database.DeleteResult result = Database.delete(curso, false);
        Test.stopTest();
        // Verify 
        // In this case the deletion should have been stopped by the trigger,
        // so verify that we got back an error.
        System.assert(result.isSuccess());
        //System.assert(result.getErrors().size() > 0);
    }
}